#!/bin/bash
### BEGIN INIT INFO
# Provides:          polaric-webapp
# Required-Start:    $network $local_fs $remote_fs $time
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

       
DESC="Polaric Server Webapp"
NAME=polaric-webapp
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
POLARIC_SHUTDOWN=30


if [ `id -u` -ne 0 ]; then
        echo "You need root privileges to run this script"
        exit 1
fi

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

. /lib/lsb/init-functions

if [ -r /etc/default/rcS ]; then
        . /etc/default/rcS
fi




case "$1" in 
   start) 
         #
         # Mapserver/ka-map specific things 
         #
         rm -R /tmp/wms >& /dev/null
         rm -R /tmp/wms_raster >& /dev/null
         mkdir /tmp/wms
         mkdir /tmp/wms_raster
         chown www-data.www-data /tmp/wms
         chown www-data.www-data /tmp/wms_raster
         
         # Start webserver 
         #apache2ctl restart > /dev/null
         
         log_daemon_msg "$DESC started"
         log_end_msg 0
         ;;
   
   stop)
         log_daemon_msg "$DESC stopped"
         log_end_msg 0
         ;;
         
         
  status)
        ;;         
        
  restart|force-reload)
        $0 stop $*
        sleep 1
        $0 start $*
        ;;

  try-restart)
        $0 start $*
        ;;        
        
  
   *)
      echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" 
      exit 3
      ;;
   
esac
exit 0
